### PR TITLE
Fix the hyperlink in License.rtf

### PR DESCRIPTION
**Pull request by yecril71pl**
It looks like an honest mistake made on a case-insensitive file system.  I did not update the project file because you use `\` for path separators anyway, so I assume it requires a Microsoft Windows machine to build.  It is possible to configure **NTFS** to be case-sensitive though, so the build may fail for some users.

### CODE REVIEW

**Comment by EWSoftware** [comment]
I've fixed the folder casing so that it's consistent now.  Regarding License.rtf, it needs to remain as it's included as part of the VSIX manifest.  I see no reason to add License.odt since it contains the same content as License.rtf.

**Comment by yecril71pl** [comment]
> I've fixed the folder casing so that it's consistent now. Regarding License.rtf, it needs to remain as it's included as part of the VSIX manifest. I see no reason to add License.odt since it contains the same content as License.rtf.

It is different, I have fixed the hyperlink.

**Comment by EWSoftware** [comment]
I fixed the link in the license file.  My point was that you changed the file format.  There didn't appear to be a need for that.

**Comment by yecril71pl** [comment]
> I fixed the link in the license file. My point was that you changed the file format. There didn't appear to be a need for that.

Your new hyperlink is invalid too.  I have retracted the **ODT** file and fixed the **RTF** file instead.

**Comment by EWSoftware** [comment]
The casing needed to be fixed in the license file in the root too so I've done them both.  Thanks.

**Comment by yecril71pl** [comment]
> The casing needed to be fixed in the license file in the root too so I've done them both. Thanks.

You have removed the hyperlink from the **RTF** file.  The URL in the text is styled like a hyperlink but it is not actually linked, which will be frustrating to the reader.

**Comment by EWSoftware** [comment]
I just checked it.  It's a link and is working.

**Comment by yecril71pl** [comment]
> I just checked it. It's a link and is working.

It does not work in **Safari** on **iOS** (which opens **RTF** natively).  When imported to **Apple Pages**, it shows no hyperlink.  Something is wrong with that file.

**Comment by EWSoftware** [comment]
It works in Word and WordPad on Windows so must be an Apple thing.

**Pull request closed without merging**
