### PR TITLE
Fix for PHP Tools for Visual Studio 2019

### PR DESCRIPTION
**Pull request by Miloslav**

### CODE REVIEW

**Comment by EWSoftware** [comment]
Thanks for the update.

**Comment by Miloslav** [comment]
Thank you for merge. Have a good one

**Comment by johnwc** [comment]
@EWSoftware when do you think the next release will be that will include this merge?

**Comment by EWSoftware** [comment]
@johnwc I just published the update.  It should be available for download shortly.

**Comment by johnwc** [comment]
@EWSoftware Thank you

**Pull request merged**
